twig:
    file_name_pattern: '*.twig'
    globals:
        # the value is the service's id
        logo : '@App\Services\LogoService'
        bureau : '@App\Services\BureauService'
        infos : '@App\Services\InfoService'


when@test:
    twig:
        strict_variables: true
